# Generated by Django 4.2.7 on 2023-12-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
    ]
