# Generated by Django 4.2.7 on 2023-12-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Collars'), (2, 'Leads'), (3, 'Clothes'), (4, 'Dog Treats'), (5, 'Dog Food')], default=0),
        ),
    ]
