# Generated by Django 4.2.7 on 2023-12-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Collars'), (2, 'Leads'), (3, 'Clothes'), (4, 'Dog Treats'), (5, 'Dog Food'), (6, 'Dog Bowls')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='draft',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0),
        ),
    ]
